#!/bin/bash

convert.fahrenheit () {
	local input=$1
	echo "$(awk -vinput="$input" 'BEGIN{print (input - 32) / 1.8}') C"
}

convert.mile () {
	local input=$1
	echo "$(awk -vinput="$input" 'BEGIN{print input * 1.609344}') km"
}

convert.yard () {
	local input=$1
	echo "$(awk -vinput="$input" 'BEGIN{print input / 1.0936}') m"
	echo "Who the hell still uses yards?"
}

convert.foot () {
	local input=$1
	echo "$(awk -vinput="$input" 'BEGIN{print input * 0.3048}') m"
}

convert.inch () {
	local input=$1
	echo "$(awk -vinput="$input" 'BEGIN{print input * 2.54}') cm"
}

convert.pound () {
	local input=$1
	echo "$(awk -vinput="$input" 'BEGIN{print input * 0.45359237}') kg"
}

convert.gallon () {
	local input=$1
	echo "$(awk -vinput="$input" 'BEGIN{print input / 0.2641720524}') L"
}

convert.mileperhour() {
	local input=$1
	echo "$(awk -vinput="$input" 'BEGIN{print input / 0.6213711922}') kmh"
}

get.unit () {
	local arg=$1
	arg="${arg//[[:punct:]]/}"
	echo "${arg//[[:digit:]]/}"
}

get.value () {
	local arg=$1
	echo "${arg//[[:alpha]]/}"
}

unit=$(get.unit $1)
value=$(get.value $1)

shopt -s nocasematch
case $unit in
	f)	convert.fahrenheit "$value";;
	mi)	convert.mile "$value";;
	y)	convert.yard "$value";;
	ft)	convert.foot "$value";;
	in)	convert.inch "$value";;
	lb)	convert.pound "$value";;
	gal)	convert.gallon "$value";;
	mph)	convert.mileperhour "$value";;
	*)	echo "ERROR! Unit is not supported!" >&2;;
esac
shopt -u nocasematch