#!/bin/bash

if [[ -f "${0%/*}/conversions" ]]; then
	. "${0%/*}/conversions"
else
	echo "ERROR! Cannot find conversions file." >&2
fi

unit=$(get.unit $1)
value=$(get.value $1)

shopt -s nocasematch
case $unit in
	f)	convert.fahrenheit "$value";;
	mi)	convert.mile "$value";;
	y)	convert.yard "$value";;
	ft)	convert.foot "$value";;
	in)	convert.inch "$value";;
	lb)	convert.pound "$value";;
	gal)	convert.gallon "$value";;
	mph)	convert.mileperhour "$value";;
	acre)	convert.acre "$value";;
	*)	echo "ERROR! Unit is not supported!" >&2;;
esac
shopt -u nocasematch