#!/bin/bash

if [[ -f "${0%/*}/conversions" ]]; then
	. "${0%/*}/conversions"
else
	echo "ERROR! Cannot find conversions file." >&2
fi

unit=$(get.unit $1)
value=$(get.value $1)

shopt -s nocasematch
case $unit in
	c)	convert.celsius "$value";;
	k)	convert.kelvin "$value";;
	km)	convert.kilometer "$value";;
	m)	convert.meter "$value";;
	cm)	convert.centimeter "$value";;
	kg)	convert.kilogram "$value";;
	l)	convert.liter "$value";;
	st)	convert.stone "$value";;
	kmh)	convert.kmperhour "$value";;
	*)	echo "ERROR! Unit is not supported!" >&2;;
esac
shopt -u nocasematch